export const GET_POSTS: "POST/GET_POSTS" = "POST/GET_POSTS";
export const GET_POSTS_SUCCESS: "POST/GET_POSTS_SUCCESS" = "POST/GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL: "POST/GET_POSTS_FAIL" = "POST/GET_POSTS_FAIL";

export const CREATE: 'POST/CREATE' = 'POST/CREATE';
export const CREATE_SUCCESS: 'POST/CREATE_SUCCESS' = 'POST/CREATE_SUCCESS';
export const CREATE_FAIL: 'POST/CREATE_FAIL' = 'POST/CREATE_FAIL';

export const UPDATE: "POST/UPDATE" = "POST/UPDATE";
export const UPDATE_SUCCESS: "POST/UPDATE_SUCCESS" = "POST/UPDATE_SUCCESS";
export const UPDATE_FAIL: "POST/UPDATE_FAIL" = "POST/UPDATE_FAIL";

export const DELETE: "POST/DELETE" = "POST/DELETE";
export const DELETE_SUCCESS: "POST/DELETE_SUCCESS" = "POST/DELETE_SUCCESS";
export const DELETE_FAIL: "POST/DELETE_FAIL" = "POST/DELETE_FAIL";
