
export const AUTHENTICATE: "USER/AUTHENTICATE" = "USER/AUTHENTICATE";
export const AUTHENTICATE_SUCCESS: "USER/AUTHENTICATE_SUCCESS" = "USER/AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAIL: "USER/AUTHENTICATE_FAIL" = "USER/AUTHENTICATE_FAIL";

export const GET_PROFILE: "USER/GET_PROFILE" = "USER/GET_PROFILE";
export const GET_PROFILE_SUCCESS: "USER/GET_PROFILE_SUCCESS" = "USER/GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL: "USER/GET_PROFILE_FAIL" = "USER/GET_PROFILE_FAIL";

export const CREATE: 'USER/CREATE' = 'USER/CREATE';
export const CREATE_SUCCESS: 'USER/CREATE_SUCCESS' = 'USER/CREATE_SUCCESS';
export const CREATE_FAIL: 'USER/CREATE_FAIL' = 'USER/CREATE_FAIL';

export const UPDATE: "USER/UPDATE" = "USER/UPDATE";
export const UPDATE_SUCCESS: "USER/UPDATE_SUCCESS" = "USER/UPDATE_SUCCESS";
export const UPDATE_FAIL: "USER/UPDATE_FAIL" = "USER/UPDATE_FAIL";

export const DELETE: "USER/DELETE" = "USER/DELETE";
export const DELETE_SUCCESS: "USER/DELETE_SUCCESS" = "USER/DELETE_SUCCESS";
export const DELETE_FAIL: "USER/DELETE_FAIL" = "USER/DELETE_FAIL";

export const DISCONNECT: "USER/DISCONNECT" = "USER/DISCONNECT";
